export const FETCH_LEARNERS = 'FETCH_LEARNERS';
export const ADD_LEARNER = 'ADD_LEARNER';
export const DELETE_LEARNER = 'DELETE_LEARNER';
export const FETCH_LEARNER_BY_ID = 'FETCH_LEARNER_BY_ID'
export const SELECT_SUBJECT = 'SELECT_SUBJECT';
export const DELETE_LEARNER_SUBJECT = 'DELETE_LEARNER_SUBJECT';
export const FETCH_LEARNER_CLASSMATES = 'FETCH_LEARNER_CLASSMATES';

export const FETCH_GRADES = 'FETCH_GRADES';
export const ADD_GRADE = 'ADD_GRADE';

export const FETCH_SUBJECTS = 'FETCH_SUBJECTS';
export const ADD_SUBJECT = 'ADD_SUBJECT';
export const FETCH_SUBJECT_BY_ID = 'FETCH_SUBJECT_BY_ID';
export const UPDATE_SUBJECT = "UPDATE_SUBJECT";

export const ADD_SUBJECT_SUCCESS = "ADD_SUBJECT_SUCCESS";
export const ADD_SUBJECT_FAILURE = "ADD_SUBJECT_FAILURE";
export const ADD_SUBJECT_STARTED = "ADD_SUBJECT_STARTED";
export const DELETE_SUBJECT = 'DELETE_SUBJECT';


export const FETCH_LESSONS = 'FETCH_LESSONS';
export const ADD_LESSON = 'ADD_LESSON';
export const DELETE_LESSON = 'DELETE_LESSON';

export const FETCH_TEACHERS = 'FETCH_TEACHERS';
export const ADD_TEACHER = 'ADD_TEACHER';
export const DELETE_TEACHER = 'DELETE_TEACHER';

export const FETCH_DAYS = 'FETCH_DAYS';
export const ADD_DAY = 'ADD_DAY';



export const OPEN_ADD_SUBJECTS_MODAL = "OPEN_ADD_SUBJECTS_MODAL";
export const CLOSE_ADD_SUBJECT_MODAL = "CLOSE_ADD_SUBJECT_MODAL";

export const OPEN_SHOW_SUBJECTS_MODAL = "OPEN_SHOW_SUBJECTS_MODAL";
export const CLOSE_SHOW_SUBJECTS_MODAL = "CLOSE_SHOW_SUBJECTS_MODAL";

export const OPEN_UPDATE_SUBJECT_MODAL = "OPEN_UPDATE_SUBJECT_MODAL";
export const CLOSE_UPDATE_SUBJECT_MODAL = "CLOSE_UPDATE_SUBJECT_MODAL";



export const OPEN_ADD_LEARNER_MODAL = "OPEN_ADD_LEARNER_MODAL";
export const CLOSE_ADD_LEARNER_MODAL = "CLOSE_ADD_LEARNER_MODAL";

export const OPEN_SHOW_LEARNERS_MODAL = "OPEN_SHOW_LEARNERS_MODAL";
export const CLOSE_SHOW_LEARNERS_MODAL = "CLOSE_SHOW_LEARNERS_MODAL";

export const OPEN_UPDATE_LEARNER_MODAL = "OPEN_UPDATE_LEARNER_MODAL";
export const CLOSE_UPDATE_LEARNER_MODAL = "CLOSE_UPDATE_LEARNER_MODAL";



export const OPEN_ADD_TEACHER_MODAL = "OPEN_ADD_TEACHER_MODAL";
export const CLOSE_ADD_TEACHER_MODAL = "CLOSE_ADD_TEACHER_MODAL";

export const OPEN_SHOW_TEACHERS_MODAL = "OPEN_SHOW_TEACHERS_MODAL";
export const CLOSE_SHOW_TEACHERS_MODAL = "CLOSE_SHOW_TEACHERS_MODAL";

export const OPEN_UPDATE_TEACHER_MODAL = "OPEN_UPDATE_TEACHER_MODAL";
export const CLOSE_UPDATE_TEACHER_MODAL = "CLOSE_UPDATE_TEACHER_MODAL";



export const OPEN_ADD_LESSON_MODAL = "OPEN_ADD_LESSON_MODAL";
export const CLOSE_ADD_LESSON_MODAL = "CLOSE_ADD_LESSON_MODAL";

export const OPEN_SHOW_LESSONS_MODAL = "OPEN_SHOW_LESSONS_MODAL";
export const CLOSE_SHOW_LESSONS_MODAL = "CLOSE_SHOW_LESSONS_MODAL";

export const OPEN_UPDATE_LESSON_MODAL = "OPEN_UPDATE_LESSON_MODAL";
export const CLOSE_UPDATE_LESSON_MODAL = "CLOSE_UPDATE_LESSON_MODAL";

export const OPEN_SELECT_SUBJECT_MODAL = "OPEN_SELECT_SUBJECT_MODAL";
export const CLOSE_SELECT_SUBJECT_MODAL = "CLOSE_SELECT_SUBJECT_MODAL";


export const OPEN_LEARNER_SUBJECTS_MODAL = "OPEN_LEARNER_SUBJECTS_MODAL";
export const CLOSE_LEARNER_SUBJECTS_MODAL = "CLOSE_LEARNER_SUBJECTS_MODAL";

export const OPEN_CLASSMATES_MODAL = "OPEN_CLASSMATES_MODAL";
export const CLOSE_CLASSMATES_MODAL = "CLOSE_CLASSMATES_MODAL";



